import { CheckBox } from "std-widgets.slint";
import { Callabler } from "callabler.slint";
import { Translations } from "translations.slint";
import { PopupBase } from "popup_base.slint";
import { PopupCenteredText } from "popup_centered_text.slint";
import { Settings } from "settings.slint";

export component PopupMoveFolders inherits Rectangle {
    private property <length> popup_width: 500px;
    private property <length> popup_min_height: 150px;
    in-out property <string> folder_name: "";
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        popup_min_height: popup_min_height;
        x: (parent.width - popup_width) / 2.0;
        y: (parent.height - self.height) / 2.0;
        title_text <=> Translations.popup_move_title_text;

        VerticalLayout {
            PopupCenteredText {
                text: Translations.move_confirmation_text + "\n" + folder_name;
            }

            Rectangle {height: 5px;}

            VerticalLayout {
                HorizontalLayout {
                    alignment: center;
                    CheckBox {
                        text <=> Translations.popup_move_copy_checkbox_text;
                        checked <=> Settings.popup_move_copy_mode;
                    }
                }
                Rectangle {height: 5px;}

                HorizontalLayout {
                    alignment: center;
                    CheckBox {
                        text <=> Translations.popup_move_preserve_folder_checkbox_text;
                        checked <=> Settings.popup_move_preserve_folder_structure;
                    }
                }
            }
        }

        ok_clicked => {
            Callabler.move_items(folder_name);
        }
    }

    show_popup() => {
        popup_window.show();
    }
}
